[package]
name = "journey"
version = "0.0.1"
authors = ["Alejandro Socorro <alejandrosocorro@gmail.com>"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
